
[package]
name = "sophon-wasm-fuzz"
version = "0.0.1"
authors = ["Pat Hickey phickey@fastly.com"]
publish = false
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[package.metadata]
cargo-fuzz = true

[dependencies.sophon-wasm]
path = ".."
[dependencies.libfuzzer-sys]
git = "https://github.com/rust-fuzz/libfuzzer-sys.git"

[dependencies.mktemp]
version = "0.3.1"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "deserialize"
path = "fuzz_targets/deserialize.rs"
